blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussion
    url: https://github.com/xjiaxiang/github-playground/discussions
    about: Ask questions and discuss with other community members
  - name: ðŸ”’ Security Issue
    url: https://github.com/xjiaxiang/github-playground/security/policy
    about: Report a security vulnerability
